### ISSUE TITLE
Can't change examples

### ISSUE THREAD

**Issue by Baspla** [Fus3n/infinite-sides#2]
I removed all examples in the settings and added new ones but the default examples are always added at the end of the prompt.

My guess is that the function reload_settings(self) in backend.py does not load the examples from the config.

**Comment by Fus3n** [comment]
The new [release](https://github.com/Fus3n/infinite-sides/releases/tag/1.1.0) addresses this issue along with some others, thank you for pointing it out. Please download the new one.
